name: 'notes-app'

networks:
  app-network:

volumes:
  mysql_data:

services:
  mysql:
    image: mysql:latest
#    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: notes_db
    ports:
      - "3306:3306"
    networks:
      - app-network
    volumes:
      - mysql_data:/var/lib/mysql

  user-service:
    image: ram1uj/notes-app-notes-service
#    container_name: user-service
    restart: always
    environment:
      DB_HOST: mysql
      DB_NAME: notes_db
      DB_USER: root
      DB_PASSWORD: password
    ports:
      - "8200:8200"
    depends_on:
      - mysql
    networks:
      - app-network

  notes-service:
    image: ram1uj/notes-app-notes-service
#    container_name: notes-service
    restart: always
    environment:
      DB_HOST: mysql
      DB_NAME: notes_db
      DB_USER: root
      DB_PASSWORD: password
    ports:
      - "8100:8100"
    depends_on:
      - mysql
    networks:
      - app-network

